version: '3.9'
services:
  db:
    container_name: mysql
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD:-password}'
      MYSQL_DATABASE: '${DB_DATABASE:-test}'
      MYSQL_USER: '${DB_USERNAME:-test}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    # networks:
    #   - backend

#  redis:
#    container_name: redis
#    image: 'redis:alpine'
#    ports:
#      - '${REDIS_PORT:-6379}:6379'
#    volumes:
#      - 'backend-redis:/data'
#    networks:
#      - backend
#    healthcheck:
#      test: ["CMD", "redis-cli", "ping"]
#      retries: 3
#      timeout: 5s

# networks:
#   backend:
#     external: true
# #
#volumes:
#  backend-mysql:
#    driver: local