version: '3.9'
services:
  db:
    container_name: mysql
    image: mysql:5.7
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: 'Asia/Tokyo'
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
    networks:
      - backend

#  redis:
#    container_name: redis
#    image: 'redis:alpine'
#    ports:
#      - '${REDIS_PORT:-6379}:6379'
#    volumes:
#      - 'backend-redis:/data'
#    networks:
#      - backend
#    healthcheck:
#      test: ["CMD", "redis-cli", "ping"]
#      retries: 3
#      timeout: 5s

networks:
  backend:
    external: true
#
#volumes:
#  backend-mysql:
#    driver: local